# -*- coding: utf-8 -*-
"""Day21_AM_PartA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHAgUiYUjzpi-HnSvlIuRpdOUK73lJuN

Create NumPy arrays of different dimensions (1D, 2D, 3D):

○ Perform indexing and slicing operations

○ Extract specific rows, columns, and subarrays
"""

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])


arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

print(arr1[2])

print(arr1[1:4])

print(arr2[1,2])

print(arr2[1,1:3])

print(arr3[0,1,1])

print(arr3[1, 1, 1])

"""2. Implement basic operations using NumPy (without loops):

○ Element-wise addition, subtraction, multiplication

○ Compute mean, variance, and standard deviation
"""

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)


data = np.array([10, 20, 30, 40, 50])

print(np.mean(data))
print(np.var(data))
print(np.std(data))

"""3. Demonstrate broadcasting:

○ Add a 1D array to a 2D array

○ Multiply a matrix by a scalar and a vector

○ Explain how broadcasting works in each case
"""

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20])

print(A + B)

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

"""Here B is stretched across rows of A, so, 10, 20, 30 are added to respective elements of each rows.

Note - in case if shape of B was 1 X 2, broadcasting will not take place.
"""

print(A * 2)

"""Scalar broadcasting applies to every single element"""

C = np.array([1, 0, 1])
print(A * C)

C = np.array([1, 0])
print(A * C)

"""Vector is broadcasted across rows.

Note -
Broadcasting cannot happen when C doesn't have equal number of columns as A.

4. Implement vectorised operations:

○ Compute square and cube of all elements

○ Replace all negative values with 0

○ Normalize an array (scale values between 0 and 1)
"""

sq1 = arr1**2
sq2 = arr2**2
sq3 = arr3**2

print(sq1)
print(sq2)
print(sq3)

cu1 = arr1**3
cu2 = arr2**3
cu3 = arr3**3

print(cu1)
print(cu2)
print(cu3)

def make_random_negative(arr):
    signs = np.random.choice([1, -1], size=arr.shape)
    return arr * signs

arr1_neg = make_random_negative(arr1)
arr2_neg = make_random_negative(arr2)
arr3_neg = make_random_negative(arr3)

print(arr1_neg)
print(arr2_neg)
print(arr3_neg)

arr1_no_neg = np.where(arr1_neg < 0, 0, arr1_neg)
arr2_no_neg = np.where(arr2_neg < 0, 0, arr2_neg)
arr3_no_neg = np.where(arr3_neg < 0, 0, arr3_neg)

print(arr1_no_neg)
print(arr2_no_neg)
print(arr3_no_neg)

"""Normalize (scale between 0 and 1)

Formula:

normalized

normalized=x−min(x)/max(x)−min(x)​


"""

def normalize(arr):
    return (arr - arr.min()) / (arr.max() - arr.min())

arr1_norm = normalize(arr1_no_neg)
arr2_norm = normalize(arr2_no_neg)
arr3_norm = normalize(arr3_no_neg)

print("Original with negatives:\n", arr1_neg)
print("No negatives:\n", arr1_no_neg)
print("Square:\n", sq1)
print("Cube:\n", cu1)
print("Normalized:\n", arr1_norm)

print("Original with negatives:\n", arr2_neg)
print("No negatives:\n", arr2_no_neg)
print("Square:\n", sq2)
print("Cube:\n", cu2)
print("Normalized:\n", arr2_norm)

print("Original with negatives:\n", arr3_neg)
print("No negatives:\n", arr3_no_neg)
print("Square:\n", sq3)
print("Cube:\n", cu3)
print("Normalized:\n", arr3_norm)

"""5. Given a dataset (NumPy array):

○ Find top 5 maximum values

○ Compute row-wise and column-wise sums

○ Identify indices of values greater than a threshold
"""

top5_arr1 = np.sort(arr1)[-5:]
top5_arr2 = np.sort(arr2, axis=None)[-5:]
top5_arr3 = np.sort(arr3, axis=None)[-5:]

print(arr3)

print(top5_arr1)
print(top5_arr2)
print(top5_arr3)

arr1_sum = arr1.sum()
arr1_sum

arr2

arr2_sum_row = arr2.sum(axis=1)
arr2_sum_col = arr2.sum(axis=0)
arr2_sum_row

arr2_sum_col

arr3_sum_row = arr3.sum(axis=1)
arr3_sum_col = arr3.sum(axis=0)
arr3_sum = arr3.sum(axis=2)

print(arr3)

arr3_sum_col

arr3_sum_row

arr3_sum

threshold = 30

idx_arr1 = np.where(arr1 > threshold)

idx_arr1

threshold = 7
idx_arr2 = np.where(arr2 > threshold)
print(idx_arr2)

threshold = 5
idx_arr3 = np.where(arr3 > threshold)
print(idx_arr3)

